# ab.exe -n 20 -c 20 http://127.0.0.1:8080/.well-known/test/lock/reduce-unsafe

# ab.exe -n 20 -c 20 http://127.0.0.1:8080/.well-known/test/lock/reduce-safe


###
GET http://{{host}}/.well-known/test/lock/reduce-safe

###
GET http://{{host}}/.well-known/test/lock/sleep

