###
@name={{$random.name.username}}

POST http://{{host}}/api/user/register
Content-Type: application/json

{
  "username": "{{name}}",
  "password": "password",
  "confirmPassword": "password",
  "nickname": "{{name}}",
  "mobile": "",
  "email": "{{$random.email}}"
}
###

