### 测试请求
POST http://{{host}}/.well-known/test/request/string

###
POST http://{{host}}/.well-known/test/request/string
Content-Type: text/plain

test 测试

###
POST http://{{host}}/.well-known/test/request/string
Content-Type: application/json

test 测试

###
POST http://{{host}}/.well-known/test/request/string
Content-Type: application/json

{
  "null": null,
  "string": "测试",
  "bool": true,
  "int": 12345,
  "long": 123456789012345678901234567890123456789012345678901234567890123456789012345678901234567890,
  "decimal": 123456789012345678901234567890.123456789012345678901234567890,
  "array": [1, 2, 3],
  "object": {
    "key": "值"
  }
}

###
POST http://{{host}}/.well-known/test/request/json

###
POST http://{{host}}/.well-known/test/request/json
Content-Type: text/plain

test 测试

###
POST http://{{host}}/.well-known/test/request/json
Content-Type: application/json

test 测试

###
POST http://{{host}}/.well-known/test/request/json
Content-Type: application/json

{
  "null": null,
  "string": "测试",
  "bool": true,
  "int": 12345,
  "long": 123456789012345678901234567890123456789012345678901234567890123456789012345678901234567890,
  "decimal": 123456789012345678901234567890.123456789012345678901234567890,
  "array": [1, 2, 3],
  "object": {
    "key": "值"
  }
}
