### 设置 count
GET http://{{host}}/api/test/lock/set-count?value=1

### 同步减少 count，不加锁，会超减，需多执行几次
GET http://{{host}}/api/test/lock/sync-decrease-count
# ab.exe -n 10 -c 10 http://127.0.0.1:5006/api/test/lock/sync-decrease-count

### 异步减少 count，不加锁，会超减，需多执行几次
GET http://{{host}}/api/test/lock/async-decrease-count
# ab.exe -n 10 -c 10 http://127.0.0.1:5006/api/test/lock/async-decrease-count

### 同步减少 count，加同步锁，不会超减
GET http://{{host}}/api/test/lock/sync-decrease-count-with-sync-lock
# ab.exe -n 10 -c 10 http://127.0.0.1:5006/api/test/lock/sync-decrease-count-with-sync-lock

### 同步减少 count，加异步锁，不会超减
GET http://{{host}}/api/test/lock/sync-decrease-count-with-async-lock
# ab.exe -n 10 -c 10 http://127.0.0.1:5006/api/test/lock/sync-decrease-count-with-async-lock

### 异步减少 count，加同步锁，不会超减
GET http://{{host}}/api/test/lock/async-decrease-count-with-sync-lock
# ab.exe -n 10 -c 10 http://127.0.0.1:5006/api/test/lock/async-decrease-count-with-sync-lock

### 异步减少 count，加异步锁，不会超减
GET http://{{host}}/api/test/lock/async-decrease-count-with-async-lock
# ab.exe -n 10 -c 10 http://127.0.0.1:5006/api/test/lock/async-decrease-count-with-async-lock

#=======================================================================================================================

### 同步 Thread.Sleep
GET http://{{host}}/api/test/lock/thread-sleep

### 异步 Task.Delay
GET http://{{host}}/api/test/lock/async-task-delay

### 异步 Task.Delay，加异步锁
GET http://{{host}}/api/test/lock/async-task-delay-with-async-lock
# ab.exe -n 10 -c 10 http://127.0.0.1:5006/api/test/lock/async-task-delay-with-async-lock

#=======================================================================================================================

### 测试 LockException 异常
GET http://{{host}}/api/test/lock/exception

