### 准备
< {%
    client.global.clearAll();

    const rnd = $random.name.username;
    client.global.set('username', rnd);
    // console.log('client.global', client.global);
    // request.variables.set('username', rnd);
    // console.log(.variables);
%}
GET http://{{host}}/.well-known/info

### 注册
POST http://{{host}}/api/user/register
Content-Type: application/json

{
  "username": "{{username}}",
  "password": "password",
  "confirmPassword": "password",
  "nickname": "{{username}}"
}

### 注册重复用户名
POST http://{{host}}/api/user/register
Content-Type: application/json

{
  "username": "{{username}}",
  "password": "password",
  "confirmPassword": "password",
  "nickname": "{{username}}"
}

