### 测试锁，加锁扣减
GET http://{{host}}/.well-known/test/lock/reduce-safe

### 测试锁，等待
GET http://{{host}}/.well-known/test/lock/sleep
# ab.exe -n 20 -c 20 http://127.0.0.1:5006/.well-known/test/lock/reduce-unsafe
# ab.exe -n 20 -c 20 http://127.0.0.1:5006/.well-known/test/lock/reduce-safe
