### ²âÊÔËø£¬¼ÓËø¿Û¼õ
GET http://{{host}}/.well-known/test/lock/reduce-safe

### ²âÊÔËø£¬µÈ´ı
GET http://{{host}}/.well-known/test/lock/sleep
# ab.exe -n 20 -c 20 http://127.0.0.1:5006/.well-known/test/lock/reduce-unsafe
# ab.exe -n 20 -c 20 http://127.0.0.1:5006/.well-known/test/lock/reduce-safe
