### 登录
# @name login
POST http://{{host}}/api/user/login
Content-Type: application/json

{
  "username": "admin",
  "password": "password"
}

### 用户列表
POST http://{{host}}/api/admin/user/list
Content-Type: application/json
Access-Token: {{login.response.body.$.data.accessToken}}

{
  "pageNum": 1,
  "pageSize": 10
}

