### 登录
# @name login
POST http://{{host}}/api/user/login
Content-Type: application/json

{
  "username": "admin",
  "password": "password"
}

### 创建
@username={{$timestamp}}
# @name create
POST http://{{host}}/api/admin/user/create
Content-Type: application/json
Access-Token: {{login.response.body.$.data.accessToken}}

{
  "username": "{{username}}",
  "password": "password",
  "confirmPassword": "password",
  "nickname": "{{username}}",
  "mobile": ""
}

### 创建后获取
GET http://{{host}}/api/admin/user/get?id={{create.response.body.$.data.id}}
Access-Token: {{login.response.body.$.data.accessToken}}

### 更新
POST http://{{host}}/api/admin/user/modify
Content-Type: application/json
Access-Token: {{login.response.body.$.data.accessToken}}

{
  "id": "{{create.response.body.$.data.id}}",
  "username": "{{username}}",
  "password": "password",
  "confirmPassword": "password",
  "nickname": "{{username}}",
  "mobile": "138{{$randomInt 10000000 99999999}}"
}

### 更新手机后获取
GET http://{{host}}/api/admin/user/get?id={{create.response.body.$.data.id}}
Access-Token: {{login.response.body.$.data.accessToken}}

### 删除
POST http://{{host}}/api/admin/user/remove
Access-Token: {{login.response.body.$.data.accessToken}}

{
  "id": "{{create.response.body.$.data.id}}"
}

### 删除后获取
GET http://{{host}}/api/admin/user/get?id={{create.response.body.$.data.id}}
Access-Token: {{login.response.body.$.data.accessToken}}

