@secret=jwt-secret-must-long-than-32-str
@expiresAt={{$localDatetime "yyyy-MM-dd HH:mm:ss" 1 h}} 

### JWT 编码
# @name jwtEncode
POST http://{{host}}/api/test/crypto/jwt-encode
Content-Type: application/json

{
  "secret": "{{secret}}",
  "expiresAt": "{{expiresAt}}",
  "payload": {
    "string": "test",
    "boolean": true,
    "number": 123
  }
}

### JWT 解码，正确的 secret
POST http://{{host}}/api/test/crypto/jwt-decode
Content-Type: application/json

{
  "secret": "{{secret}}",
  "token": "{{jwtEncode.response.body.$.data.token}}"
}

### JWT 解码，错误的 secret
POST http://{{host}}/api/test/crypto/jwt-decode
Content-Type: application/json

{
  "secret": "jwt-secret-must-long-than-32-str-wrong",
  "token": "{{jwtEncode.response.body.$.data.token}}"
}

### JWT 编码，已过期
@expiresAtExpired=2025-01-01 00:00:00

# @name jwtEncodeExpired
POST http://{{host}}/api/test/crypto/jwt-encode
Content-Type: application/json

{
  "secret": "{{secret}}",
  "expiresAt": "{{expiresAtExpired}}",
  "payload": {
    "string": "test",
    "boolean": true,
    "number": 123
  }
}

### JWT 解码，已过期
POST http://{{host}}/api/test/crypto/jwt-decode
Content-Type: application/json

{
  "secret": "{{secret}}",
  "token": "{{jwtEncodeExpired.response.body.$.data.token}}"
}

### BASE64 编码
# @name base64Encode
GET http://{{host}}/api/test/crypto/base64-encode?text=hello

### BASE64 解码
GET http://{{host}}/api/test/crypto/base64-decode?base64={{base64Encode.response.body.$.data.base64}}

### MD5 编码
GET http://{{host}}/api/test/crypto/md5-encode?text=hello

