@username=user1

### 注册
# {{username}} 每次都会计算，故不能到
POST http://{{host}}/api/user/register
Content-Type: application/json

{
  "username": "{{username}}",
  "password": "password",
  "confirmPassword": "password",
  "nickname": "{{username}}"
}

### 登录
# @name login
POST http://{{host}}/api/user/login
Content-Type: application/json

{
  "username": "{{username}}",
  "password": "password"
}

### 取用户信息
GET http://{{host}}/api/user/profile
Access-Token: {{login.response.body.$.data.accessToken}}

