server:
  port: 8080

logging:
  file:
    name: log\log.log

spring:
  application:
    name: ddd-example-java

  profiles:
    active: dev

  datasource:
    url: jdbc:sqlite:db.db
    driver-class-name: org.sqlite.JDBC
    username:
    password:

  # 关闭 Redisson 自动配置，手工创建 RedissonClient
  autoconfigure:
    exclude:
      - org.redisson.spring.starter.RedissonAutoConfigurationV2

app:
  user-jwt-expires-day: 30
  user-jwt-secret: user-jwt-secret
#  lock-service: redisson
#  redisson-address: redis://localhost:6379
#  redisson-password:
#  redisson-database: 0


