spring:
  application:
    name: ddd-example-java

  datasource:
    url: jdbc:sqlite:../db.db
    driver-class-name: org.sqlite.JDBC
    username:
    password:

application:
  user-jwt-expires-day: 30
  user-jwt-secret: jwt-secret
